Repository wecode-bootcamp-korea/11-BeerBnB-frontend, pull requests merged in 2020-09, with the labels that each got.

#2 [Beer_BnB] Modify: Styled-Component 적용 초기세팅 수정
  package-lock.json
  package.json
  public/index.html
  src/Styles/GlobalStyle.js
  src/Styles/Theme.js
  src/Styles/common.scss
  src/Styles/mixin.js
  src/Styles/reset.scss
  src/index.js
Labels: Status: 리뷰 요청

#4 [이조은] Refactor: nav 멘토님 리뷰 반영
  .vscode/settings.json
  src/Components/Nav/Nav.js
  src/Components/Nav/NavSvg.js
Labels: Status: 리뷰 요청

#3 [최예흠][Feature/ProductList_main_contents] Modify: 코드 리팩토링 완료
  src/Components/Nav/Nav.js
  src/Pages/ProductList/AsideMap/AsideMap.js
  src/Pages/ProductList/ProductList.js
  src/Pages/ProductList/ProductListMain/MainContents/MainContents.js
  src/Pages/ProductList/ProductListMain/MainContents/MainContentsItems/MainContentsItems.js
  src/Pages/ProductList/ProductListMain/MainContents/MainContentsItems/MainItemImgSlide/MainItemImgSlide.js
  src/Pages/ProductList/ProductListMain/MainContents/ProductListMainFooter/FooterNextPrevBtn/FooterNextPrevBtnSvg.js
  src/Pages/ProductList/ProductListMain/MainContents/ProductListMainFooter/ProductListMainFooter.js
  src/Pages/ProductList/ProductListMain/MainContents/ProductListMainFooter/ProductListPageBtn/ProductListPageBtn.js
  src/Pages/ProductList/ProductListMain/MainHeader/HeaderOption/HeaderOption.js
  src/Pages/ProductList/ProductListMain/MainHeader/MainHeader.js
  src/Pages/ProductList/ProductListMain/ProductListMain.js
  src/Pages/ProductList/ProductListSvg/ProductListSvg.js
  src/Styles/mixin.js
Labels: Status: Accepted

#1 [최예흠][Feature/ProductList_main_header] Add: main header layout 구현 완료
  src/Pages/ProductList/ProductList.js
  src/Pages/ProductList/ProductListMain/MainHeader/HeaderOption/BedroomModal/BedroomModal.js
  src/Pages/ProductList/ProductListMain/MainHeader/HeaderOption/HeaderOption.js
  src/Pages/ProductList/ProductListMain/MainHeader/HeaderOption/PaymentModal/PaymentModal.js
  src/Pages/ProductList/ProductListMain/MainHeader/HeaderOption/RefundPolicyModal/RefundPolicyModal.js
  src/Pages/ProductList/ProductListMain/MainHeader/HeaderOption/RoomsTypeModal/RoomsTypeModal.js
  src/Pages/ProductList/ProductListMain/MainHeader/MainHeader.js
Labels: Status: 리뷰 요청

#5 [황연욱][feature/ProductDetail_roomIntroduce--layout] Add: ProductDetail RoomIntroduce 부분 레이아웃 작업 완료 Refactor:리뷰사항 반영 완료
  public/Images/ProductDetail/RoomImg/leftBig.webp
  public/Images/ProductDetail/RoomImg/right1.webp
  public/Images/ProductDetail/RoomImg/right2.webp
  public/Images/ProductDetail/RoomImg/right3.webp
  public/Images/ProductDetail/RoomImg/right4.webp
  pull_request_template.md
  src/Pages/ProductDetail/ProductDetail.js
  src/Pages/ProductDetail/RoomIntroduce/ImgArea/ImgArea.js
  src/Pages/ProductDetail/RoomIntroduce/RoomIntroduce.js
  src/Pages/ProductDetail/RoomIntroduce/SubTitle/InteractionBtn.js
  src/Pages/ProductDetail/RoomIntroduce/SubTitle/SubTitle.js
  src/Pages/ProductDetail/SVG/ProductDetailSvg.js
Labels: Status: 리뷰 요청

#7 [황연욱][ProductDetail_RoomInformation_Header--layout] Add: RoomInformation Header부분 추가
  public/Images/ProductDetail/wecodeimg.png
  src/Pages/ProductDetail/ProductDetail.js
  src/Pages/ProductDetail/RoomInformation/InformationHeader/InformationHeader.js
  src/Pages/ProductDetail/RoomInformation/RoomInformation.js
  src/Styles/mixin.js
Labels: Status: Accepted

#6 [이조은] Refactor: 멘토님 리뷰 반영
  src/Components/Nav/Components/LoginModal.js
  src/Components/Nav/Components/ProfileDetail.js
  src/Components/Nav/Components/ReusableStyle.js
  src/Components/Nav/Components/SignupModal.js
  src/Components/Nav/Components/SignupModalEmail.js
  src/Components/Nav/Nav.js
  src/Components/Nav/NavSvg.js
Labels: Status: Accepted

#8 [황연욱][feature/ProductDetail_RoomInformation_RoomCondition--layout] Add: 룸 컨디션 안내페이지 추가
  src/Pages/ProductDetail/ProductDetail.js
  src/Pages/ProductDetail/RoomInformation/RoomCondition/RoomCondition.js
  src/Pages/ProductDetail/RoomInformation/RoomInformation.js
  src/Pages/ProductDetail/SVG/ProductDetailSvg.js
Labels: Status: 리뷰 요청

#9 [최예흠][feature/ProductList_main_imgSlide]Add: ProductList main 이미지 슬라이더 기능 추가
  public/Images/ProductList/leftBig.webp
  public/Images/ProductList/right1.webp
  public/Images/ProductList/right2.webp
  public/Images/ProductList/right3.webp
  public/Images/ProductList/right4.webp
  src/Pages/ProductList/ProductListMain/MainContents/MainContentsItems/MainContentsItems.js
  src/Pages/ProductList/ProductListMain/MainContents/MainContentsItems/MainItemImgSlide/CarouselSlide/CarouselSlide.js
  src/Pages/ProductList/ProductListMain/MainContents/MainContentsItems/MainItemImgSlide/ImgSlideMoveBtn/ImgSlideMoveBtn.js
  src/Pages/ProductList/ProductListMain/MainContents/MainContentsItems/MainItemImgSlide/MainItemImgSlide.js
  src/Pages/ProductList/ProductListMain/MainContents/ProductListMainFooter/FooterNextPrevBtn/FooterNextPrevBtn.js
  src/Pages/ProductList/ProductListMain/MainContents/ProductListMainFooter/ProductListMainFooter.js
  src/Pages/ProductList/ProductListSvg/ProductListSvg.js
Labels: Status: Accepted

#10 [최예흠][feature/ProductList_header_RefundPolicyModal] Modify: 머지 충돌 해결 완료
  src/Pages/ProductList/ProductList.js
  src/Pages/ProductList/ProductListMain/MainContents/MainContents.js
  src/Pages/ProductList/ProductListMain/MainContents/ProductListMainFooter/FooterNextPrevBtn/FooterNextPrevBtn.js
  src/Pages/ProductList/ProductListMain/MainContents/ProductListMainFooter/ProductListMainFooter.js
  src/Pages/ProductList/ProductListMain/MainContents/ProductListMainFooter/ProductListPageBtn/ProductListPageBtn.js
  src/Pages/ProductList/ProductListMain/MainHeader/FilterToggle/FilterModal/BedroomModal/BedroomModal.js
  src/Pages/ProductList/ProductListMain/MainHeader/FilterToggle/FilterModal/FilterModal.js
  src/Pages/ProductList/ProductListMain/MainHeader/FilterToggle/FilterModal/ModalBottom/ModalBottom.js
  src/Pages/ProductList/ProductListMain/MainHeader/FilterToggle/FilterModal/PaymentModal/PaymentModal.js
  src/Pages/ProductList/ProductListMain/MainHeader/FilterToggle/FilterModal/RefundPolicyModal/RefundPolicyModal.js
  src/Pages/ProductList/ProductListMain/MainHeader/FilterToggle/FilterModal/RoomsTypeModal/RoomsTypeModal.js
  src/Pages/ProductList/ProductListMain/MainHeader/FilterToggle/FilterToggle.js
  src/Pages/ProductList/ProductListMain/MainHeader/HeaderOption/HeaderOption.js
  src/Pages/ProductList/ProductListMain/MainHeader/HeaderOption/RefundPolicyModal/RefundPolicyModal.js
  src/Pages/ProductList/ProductListMain/MainHeader/MainHeader.js
  src/Pages/ProductList/ProductListMain/ProductListMain.js
  src/Pages/ProductList/ProductListSvg/ProductListSvg.js
  src/Routes.js
Labels: Status: Accepted

#11 [황연욱][feature/ProductDetail_RoomInformation_BedType--layout] Add: 침대 / 침구 유형 부분 추가 Refactor: 코드리뷰사항 반영
  public/data/ProductDetailData.json
  pull_request_template.md
  src/Pages/ProductDetail/ProductDetail.js
  src/Pages/ProductDetail/RoomInformation/BedType/BedType.js
  src/Pages/ProductDetail/RoomInformation/Description/Description.js
  src/Pages/ProductDetail/RoomInformation/InformationHeader/InformationHeader.js
  src/Pages/ProductDetail/RoomInformation/RoomCondition/RoomCondition.js
  src/Pages/ProductDetail/RoomInformation/RoomInfoComponent/Title.js
  src/Pages/ProductDetail/RoomInformation/RoomInformation.js
  src/Pages/ProductDetail/RoomIntroduce/ImgArea/ImgArea.js
  src/Pages/ProductDetail/RoomIntroduce/RoomIntroduce.js
  src/Pages/ProductDetail/RoomIntroduce/SubTitle/SubTitle.js
  src/Pages/ProductDetail/SVG/ProductDetailSvg.js
Labels: Status: 리뷰 요청

#12 [이조은] Add: footer 레이아웃 완료
  src/Components/Footer/Footer.js
  src/Components/Footer/FooterSvg.js
Labels: Status: Accepted

#14 [이조은] Add: main 레이아웃
  src/Pages/Main/Main.js
Labels: Status: 리뷰 요청

#13 [최예흠][Feature/ProductList header roomsTypeModal] Add: 레이아웃 구성 및 기능 구현 완료
  public/data/productListData.json
  src/Pages/ProductList/ProductListMain/MainContents/MainContents.js
  src/Pages/ProductList/ProductListMain/MainContents/MainContentsItems/MainContentsItems.js
  src/Pages/ProductList/ProductListMain/MainContents/MainContentsItems/MainItemImgSlide/MainItemImgSlide.js
  src/Pages/ProductList/ProductListMain/MainContents/ProductListMainFooter/ProductListMainFooter.js
  src/Pages/ProductList/ProductListMain/MainHeader/FilterToggle/FilterModal/FilterModal.js
  src/Pages/ProductList/ProductListMain/MainHeader/FilterToggle/FilterModal/ModalBottom/ModalBottom.js
  src/Pages/ProductList/ProductListMain/MainHeader/FilterToggle/FilterModal/RefundPolicyModal/RefundPolicyModal.js
  src/Pages/ProductList/ProductListMain/MainHeader/FilterToggle/FilterModal/RoomsTypeModal/RoomsTypeModal.js
  src/Pages/ProductList/ProductListMain/MainHeader/FilterToggle/FilterToggle.js
  src/Pages/ProductList/ProductListMain/MainHeader/MainHeader.js
  src/Pages/ProductList/ProductListSvg/ProductListSvg.js
  src/Styles/GlobalStyle.js
Labels: Status: 수정 요청

#16 [황연욱][feature/ProductDetail_Amenity--layout] Add: Amenity 레이아웃 추가, Refactor: 코드리뷰사항 반영
  public/data/ProductDetailData.json
  src/Components/Footer/Footer.js
  src/Pages/ProductDetail/IconMatch/IconMatch.js
  src/Pages/ProductDetail/ProductDetail.js
  src/Pages/ProductDetail/ProductDetailComponent/Title.js
  src/Pages/ProductDetail/RoomInformation/Amenities/Amenities.js
  src/Pages/ProductDetail/RoomInformation/BedType/BedType.js
  src/Pages/ProductDetail/RoomInformation/InformationHeader/InformationHeader.js
  src/Pages/ProductDetail/RoomInformation/RoomCondition/RoomCondition.js
  src/Pages/ProductDetail/RoomInformation/RoomInformation.js
Labels: Status: Accepted

#17 [황연욱][feature/ProductDetail_ToKnowList--layout] Add: ToKnowList 레이아웃 추가 Refactor: 코드리뷰사항 반영, Conflict해결 완료
  src/Pages/ProductDetail/ProductDetail.js
  src/Pages/ProductDetail/RoomIntroduce/ImgArea/ImgArea.js
  src/Pages/ProductDetail/ToKnowList/List/List.js
  src/Pages/ProductDetail/ToKnowList/ToKnowList.js
Labels: Status: 리뷰 요청

#15 [이조은] Refactor: 멘토님 리뷰 반영
  package-lock.json
  package.json
  src/Components/Nav/Components/LoginModal.js
  src/Components/Nav/Components/ProfileDetail.js
  src/Components/Nav/Components/ReusableStyle.js
  src/Components/Nav/Components/SignupModal.js
  src/Components/Nav/Components/SignupModalEmail.js
  src/Components/Nav/Nav.js
  src/Components/Nav/NavSvg.js
  src/Routes.js
  src/config.js
Labels: Status: Accepted

#25 [이조은] Modify: map함수에 key prop 추가
  src/Components/Footer/Footer.js
  src/Components/Footer/FooterSvg.js
Labels: Status: 리뷰 요청

#24 [이조은] Modify: nav 오류 수정
  src/Components/Nav/Nav.js
  src/Routes.js
Labels: Status: 리뷰 요청

#23 [이조은] Modify: map 함수에 index 추가
  src/Pages/Main/Main.js
Labels: Status: 리뷰 요청

#18 [최예흠][feature/ProductList_header_PaymentModal] Refactor: 코드 리뷰사항 반영 완료
  public/Images/ProductList/payment.png
  src/Pages/ProductList/ProductList.js
  src/Pages/ProductList/ProductListMain/AsideMap/AsideMap.js
  src/Pages/ProductList/ProductListMain/MainContents/MainContents.js
  src/Pages/ProductList/ProductListMain/MainContents/MainContentsItems/MainContentsItems.js
  src/Pages/ProductList/ProductListMain/MainContents/MainContentsItems/MainItemImgSlide/CarouselSlide/CarouselSlide.js
  src/Pages/ProductList/ProductListMain/MainHeader/FilterToggle/FilterModal/FilterModal.js
  src/Pages/ProductList/ProductListMain/MainHeader/FilterToggle/FilterModal/ModalBottom/ModalBottom.js
  src/Pages/ProductList/ProductListMain/MainHeader/FilterToggle/FilterModal/PaymentModal/MinMaxPrice/MinMaxPrice.js
  src/Pages/ProductList/ProductListMain/MainHeader/FilterToggle/FilterModal/PaymentModal/PaymentModal.js
  src/Pages/ProductList/ProductListMain/MainHeader/FilterToggle/FilterModal/RefundPolicyModal/RefundPolicyModal.js
  src/Pages/ProductList/ProductListMain/MainHeader/FilterToggle/FilterModal/RoomsTypeModal/RoomsTypeModal.js
  src/Pages/ProductList/ProductListMain/MainHeader/FilterToggle/FilterToggle.js
  src/Pages/ProductList/ProductListMain/MainHeader/MainHeader.js
  src/Pages/ProductList/ProductListMain/ProductListMain.js
  src/Styles/GlobalStyle.js
  src/config.js
Labels: Status: 리뷰 요청

#20 [황연욱] [feature/ProductDetail_Calender] Add: 체크인 파트 레이아웃 추가, Redux 적용 Refactor: 코드리뷰사항 반영
  package-lock.json
  package.json
  src/Pages/ProductDetail/ProductDetail.js
  src/Pages/ProductDetail/RoomInformation/DayPicker/DayPicker.js
  src/Pages/ProductDetail/RoomInformation/RoomInformation.js
  src/container/DayPickerContainer.js
  src/index.js
  src/modules/ProducDetail/dayPicker.js
  src/modules/index.js
Labels: Status: 리뷰 요청

#19 [최예흠][feature/Product_header_InstantModal] Conflict 해결 완료
  src/Pages/ProductDetail/ProductDetail.js
  src/Pages/ProductDetail/RoomInformation/Amenities/Amenities.js
  src/Pages/ProductDetail/RoomInformation/DayPicker/DayPicker.js
  src/Pages/ProductDetail/RoomInformation/InformationHeader/InformationHeader.js
  src/Pages/ProductDetail/RoomInformation/RoomInformation.js
  src/Pages/ProductDetail/RoomIntroduce/ImgArea/ImgArea.js
  src/Pages/ProductDetail/RoomIntroduce/RoomIntroduce.js
  src/Pages/ProductDetail/ToKnowList/ToKnowList.js
  src/Pages/ProductList/ProductListMain/MainHeader/FilterToggle/FilterModal/BedroomModal/BedroomModal.js
  src/Pages/ProductList/ProductListMain/MainHeader/FilterToggle/FilterModal/FilterModal.js
  src/Pages/ProductList/ProductListMain/MainHeader/FilterToggle/FilterModal/InstantModal/InstantModal.js
  src/Pages/ProductList/ProductListMain/MainHeader/FilterToggle/FilterModal/MovingButton/MovingButton.js
  src/Pages/ProductList/ProductListMain/MainHeader/FilterToggle/FilterModal/RefundPolicyModal/RefundPolicyModal.js
  src/Pages/ProductList/ProductListMain/MainHeader/FilterToggle/FilterToggle.js
  src/Pages/ProductList/ProductListMain/MainHeader/MainHeader.js
  src/Routes.js
  src/config.js
  src/modules/ProducDetail/productDetail.js
  src/modules/index.js
Labels: Status: Accepted

#22 [이조은] Add: 구글 로그인 로직 구현
  public/index.html
  src/Components/Nav/Components/GoogleSignIn/GooglePopUp.js
  src/Components/Nav/Components/GoogleSignIn/GoogleSignIn.js
  src/Routes.js
Labels: Status: 리뷰 요청

#28 [11기 최예흠][feature/ProductList_ApplyRedux]Refactor:Redux 적용 리팩토링
  src/Pages/ProductList/AsideMap/AsideMap.js
  src/Pages/ProductList/ProductList.js
  src/Pages/ProductList/ProductListMain/MainContents/MainContents.js
  src/Pages/ProductList/ProductListMain/MainContents/MainContentsItems/MainContentsItems.js
  src/Pages/ProductList/ProductListMain/MainContents/ProductListMainFooter/ProductListMainFooter.js
  src/Pages/ProductList/ProductListMain/MainHeader/FilterToggle/FilterModal/FilterModal.js
  src/Pages/ProductList/ProductListMain/MainHeader/FilterToggle/FilterModal/InstantModal/InstantModal.js
  src/Pages/ProductList/ProductListMain/MainHeader/FilterToggle/FilterModal/ModalBottom/ModalBottom.js
  src/Pages/ProductList/ProductListMain/MainHeader/FilterToggle/FilterModal/RefundPolicyModal/RefundPolicyModal.js
  src/Pages/ProductList/ProductListMain/MainHeader/FilterToggle/FilterModal/RoomsTypeModal/RoomsTypeModal.js
  src/Pages/ProductList/ProductListMain/MainHeader/FilterToggle/FilterToggle.js
  src/Pages/ProductList/ProductListMain/MainHeader/MainHeader.js
  src/Pages/ProductList/ProductListMain/ProductListMain.js
  src/modules/ProductList/productList.js
  src/modules/index.js
Labels: Status: 리뷰 요청

#26 [황연욱][feature/ProductDetail_Reservation] Add: Reservaation 파트 추가, Refactor: 코드리뷰사항 반영, Conflict 해결
  src/Pages/ProductDetail/ProductDetail.js
  src/Pages/ProductDetail/ProductDetailComponent/ReviewInfo.js
  src/Pages/ProductDetail/RoomInformation/DayPicker/DayPicker.js
  src/Pages/ProductDetail/RoomInformation/Reservation/PriceInfo/Fee/Fee.js
  src/Pages/ProductDetail/RoomInformation/Reservation/PriceInfo/PriceInfo.js
  src/Pages/ProductDetail/RoomInformation/Reservation/Reservation.js
  src/Pages/ProductDetail/RoomInformation/RoomInformation.js
  src/Pages/ProductDetail/RoomIntroduce/SubTitle/SubTitle.js
  src/Pages/ProductDetail/SVG/ProductDetailSvg.js
  src/config.js
  src/container/DayPickerContainer.js
  src/modules/ProducDetail/productDetail.js
Labels: Status: 리뷰 요청

#27 [이조은] Add: searchBox 추가
  src/Pages/Main/SearchBox/SearchBox.js
  src/Pages/Main/SearchBox/SearchBoxSvg.js
  src/Pages/Main/SearchBox/SearchItem/Dates.js
  src/Pages/Main/SearchBox/SearchItem/Guest.js
  src/Pages/Main/SearchBox/SearchItem/Location.js
Labels: Status: 리뷰 요청

#29 [이조은] Modify: google 로그인 합침
  src/Components/Nav/Components/LoginModal.js
  src/Components/Nav/Components/SignupModal.js
  src/Routes.js
Labels: Status: 리뷰 요청

#32 [황연욱][feature/ProductDetail_Review]Add: Review페이지 완성 인피니티 스크롤 구현
  src/Pages/ProductDetail/ProductDetail.js
  src/Pages/ProductDetail/ProductDetailComponent/ReviewInfo.js
  src/Pages/ProductDetail/ProductDetailComponent/Spinner.js
  src/Pages/ProductDetail/Reviews/Average/Average.js
  src/Pages/ProductDetail/Reviews/ReviewItems/ReviewItems.js
  src/Pages/ProductDetail/Reviews/ReviewModal/ReviewModal.js
  src/Pages/ProductDetail/Reviews/ReviewModule/useAverageData.js
  src/Pages/ProductDetail/Reviews/ReviewModule/useReviewData.js
  src/Pages/ProductDetail/Reviews/ReviewTitle/ReviewTitle.js
  src/Pages/ProductDetail/Reviews/Reviews.js
  src/Pages/ProductDetail/RoomInformation/InformationHeader/InformationHeader.js
  src/Pages/ProductDetail/RoomInformation/Reservation/Reservation.js
  src/Pages/ProductDetail/SVG/ProductDetailSvg.js
  src/Pages/ProductDetail/constants.js
  src/Pages/ProductDetail/hooks/review.js
  src/config.js
  src/modules/ProducDetail/reviewModal.js
  src/modules/index.js
Labels: Status: 리뷰 요청

#34 [11기 최예흠][feature/ProductList_AsideMap]Add: Google Map 기능 추가 및 라벨, mini contents 생성 완료
  package-lock.json
  package.json
  public/Images/ProductList/leftBig.webp
  public/Images/ProductList/right1.webp
  public/Images/ProductList/right2.webp
  public/Images/ProductList/right3.webp
  src/Pages/ProductList/AsideMap/AsideMap.js
  src/Pages/ProductList/AsideMap/Key.js
  src/Pages/ProductList/AsideMap/LabelContent/ContentModal/ContentModal.js
  src/Pages/ProductList/AsideMap/LabelContent/LabelContent.js
  src/Pages/ProductList/ProductList.js
  src/Pages/ProductList/ProductListMain/MainContents/MainContents.js
  src/Pages/ProductList/ProductListMain/MainContents/MainContentsItems/MainContentsItems.js
  src/Pages/ProductList/ProductListMain/MainContents/MainContentsItems/MainItemImgSlide/MainItemImgSlide.js
  src/Pages/ProductList/ProductListMain/MainContents/MiniContents/MiniContents.js
  src/Pages/ProductList/ProductListMain/MainContents/ProductListMainFooter/ProductListMainFooter.js
  src/Pages/ProductList/ProductListMain/MainHeader/FilterToggle/FilterModal/FilterModal.js
  src/Pages/ProductList/ProductListMain/MainHeader/FilterToggle/FilterModal/InstantModal/InstantModal.js
  src/Pages/ProductList/ProductListMain/MainHeader/FilterToggle/FilterModal/MovingButton/MovingButton.js
  src/Pages/ProductList/ProductListMain/MainHeader/FilterToggle/FilterModal/RefundPolicyModal/RefundPolicyModal.js
  src/Pages/ProductList/ProductListMain/MainHeader/FilterToggle/FilterModal/RoomsTypeModal/RoomsTypeModal.js
  src/Pages/ProductList/ProductListMain/MainHeader/FilterToggle/FilterToggle.js
  src/Pages/ProductList/ProductListMain/MainHeader/MainHeader.js
  src/Pages/ProductList/ProductListMain/ProductListMain.js
  src/Pages/ProductList/ProductListSvg/ProductListSvg.js
  src/Pages/ProductList/SVG/ProductListSvg.js
  src/Pages/ProductList/hooks/useGetRoomsData.js
  src/modules/ProductList/productList.js
Labels: Status: 리뷰 요청

#35 [이조은] Modify: login 리듀서 파일 추가
  src/Components/Nav/Components/GoogleSignIn/GooglePopUp.js
  src/modules/index.js
Labels: Status: 리뷰 요청

#36 [이조은] Modify: 오류 수정
  src/Components/Nav/Components/GoogleSignIn/GooglePopUp.js
  src/Pages/ProductDetail/Reviews/ReviewModal/ReviewModal.js
  src/Pages/ProductDetail/RoomInformation/Reservation/PriceInfo/Fee/Fee.js
  src/Pages/ProductDetail/RoomInformation/Reservation/PriceInfo/PriceInfo.js
  src/Pages/ProductDetail/RoomInformation/Reservation/Reservation.js
  src/Pages/ProductList/ProductList.js
  src/Pages/ProductList/ProductListMain/MainContents/MainContentsItems/MainContentsItems.js
Labels: Status: 리뷰 요청
